### ISSUE TITLE
SWDF Inferrer

### ISSUE THREAD

**Issue by Hollowfier** [UPB-Lemming-Group/Lemming#37]
The updated Inferrer class generates different labels for the Graphs than the old Inferrer. This happens only for SWDF dataset. See attachment for both

**Comment by Hollowfier** [comment]
[SWDF_dataset_labels.csv](https://github.com/UPB-Lemming-Group/Lemming/files/7698636/SWDF_dataset_labels.csv)

**Comment by wangzun66** [comment]
@Hollowfier I think the reason is the change in GraphCreator. In older Inferer, GraphCreator has some false logic. Anyway, I will confirm the reason.

**Comment by Hollowfier** [comment]
@wangzun66  I think the changes you pushed last week have fixed this issue. I'll just check it a few more times before closing this ticket 👍
