### ISSUE TITLE
Check Improvement of Metrics under edegetriangles

### ISSUE THREAD

**Issue by wangzun66** [UPB-Lemming-Group/Lemming#7]
Forward

> DegreeBasedDecreasingNodeOrdering
> ForwardEdgeTriangleMetric

EdgeIteratorMetric
EdgeNumberOfSimpleTrianglesMetric
EdgeTriangleMetric
MultiThreadedNodeNeighborsCommonEdgesMetric
NodeIteratorMetric

**Comment by Hollowfier** [comment]
New issue assigned to @wangzun66
